### ISSUE TITLE
Typo in tag of v1.7.14

### ISSUE THREAD

**Issue by SaschaMann** [JuliaRegistries/TagBot#124]
The tag corresponding to `v1.7.14` is ` v1.7.144`:

![grafik](https://user-images.githubusercontent.com/20866761/76264801-0eee3d00-6263-11ea-92c9-1218d44ae4e2.png)

**Comment by christopher-dG** [comment]
Ah crap. I guess ill just bump the minor version next.

**Comment by SaschaMann** [comment]
You could also add another tag with the right name that points at the same commit if you don't want to rename `v1.7.144`
