### ISSUE TITLE
Alternate triggers (TagBot v2)

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/TagBot#125]
Closes #62 

@tkf had this awesome, delightfully simple idea (https://github.com/JuliaRegistries/TagBot/issues/62#issuecomment-591280450) to use the registry CI to create issue comments on package repos, so that package repos can run TagBot on issue comments only. This is a huge improvement because TagBot will a couple hundred times per day at most instead of something like 50,000 times.

Here's the plan in more detail:

### Registry

The General registry will have a new CI step added on merged PRs.
In this step, we parse out the repo, version, and commit from the  newly merged PR so we know where to open our issue. Then, we check if TagBot is installed on that repo and if so, we open an issue and create a comment containing the new version and commit SHA (all the info that TagBot needs). If there's an existing issue on the repo that we created for a previous version, we can use that one to avoid creating extra noise in the repos.
This work will go in RegistryCI.jl so that maintainers of all registries can use it. I already have a prototype written.
Note: This requires a user token rather than the one provided by GitHub. Using one that belongs to @JuliaTagBot makes the most sense  I think.

### TagBot

TagBot's recommended workflow configuration will change to something like this:

```yml
name: TagBot
on:
  issue_comment:
    types: created
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v2
        if: github.actor == 'JuliaTagBot'
```

Instead of fetching information from the registry, TagBot will get its info from the issue comment body which contains the version to release and the commit SHA.
For custom registries, users can change the `if` condition and a new `commenter` input to specify the user that will be making comments.

---

Am I covering all the bases here? This is still kind of a kludge but it's way better than the current kludge. I don't think that official support for cross-repo events is coming any time soon.

**Comment by SaschaMann** [comment]
> Instead of fetching information from the registry, TagBot will get its info from the issue comment body which contains the version to release and the commit SHA.

Could you explain the reason behind this?

I'm thinking about what would happen if the JuliaTagBot account was compromised, and it seems like the risk would be smaller if it's solely used as a trigger while the information is pulled from the registry. I might be wrong about this, though.

**Comment by DilumAluthge** [comment]
What are the downsides of the current cron-based approach?

If resource use is the concern, we can recommend that people run the TagBot cron job once daily. Also, keep in mind that the Julia project is not getting charged for downloads of Julia on GitHub Actions.

I guess I don't really see the problem with the cron approach. Whereas this issue-trigger approach now adds a central point of potential security concern, namely a GitHub user account that needs to be trusted.

**Comment by DilumAluthge** [comment]
Also: It's not uncommon for GitHub action runs to fail sporadically. What happens if a post-merge run fails? The tag never gets made?

**Comment by SaschaMann** [comment]
> Whereas this issue-trigger approach now adds a central point of potential security concern, namely a GitHub user account that needs to be trusted.

AFAIU the account doesn't need any access to the repo (unless it's private but in that case you can't register it to a public registry anyway) because it creates the issue like any normal user would.

**Comment by DilumAluthge** [comment]
> > Whereas this issue-trigger approach now adds a central point of potential security concern, namely a GitHub user account that needs to be trusted.
> 
> AFAIU the account doesn't need any access to the repo (unless it's private but in that case you can't register it to a public registry anyway) because it creates the issue like any normal user would.

Sure but you are trusting the contents of the issue, which means you are trusting the issue.

**Comment by tkf** [comment]
I guess TagBot can always check the comment against the General repository? In fact, I suppose JuliaTagBot can just comment `ping :)` and TagBot action can do what currently it does. Of course, if someone get the control of JuliaTagBot, they can DDoS entire Julia ecosystem which still is bad.

**Comment by SaschaMann** [comment]
> Sure but you are trusting the contents of the issue, which means you are trusting the user.

Ok, then we agree. That's what I meant in my previous comment as well : )

> Of course, if someone get the control of JuliaTagBot, they can DDoS entire Julia ecosystem which still is bad.

GitHub has rate limits, and everyone could do that by mass-opening PRs and triggering CI with their own account, too.

**Comment by christopher-dG** [comment]
Sorry to have ignored these responses -- I've been on vacation.

Let's talk about the security concern first: If we use the issue comment as information to TagBot, then the commenter needs to be trusted. Totally fair point. I personally don't see it as a giant risk to add @JuliaTagBot to the JuliaRegistries org (thereby requiring 2FA), but I can understand if you were to still consider it a threat. At the very least, TagBot should verify any information that it gets by looking in the registry, and using it solely as a ping is a good approach too.

Now let's consider what there is to gain. I'd say the two biggest things are:
- Immediate releases like we used to have with the GitHub App. TagBot becomes "properly event-based". Less clogged /actions panels on repos, etc.
- Less computers in the world running TagBot.Yes, we could just tell people to run TagBot less, but even at once a day we're still running an order of magnitude more than we need to. And we get even further from the first benefit.

Dilum's point about actions sometimes failing is a good one, that's really not ideal. I'm not sure how frequently stuff like that happens but it's not to be taken lightly. At least on the TagBot side, TagBot errors could be made more obvious to repo owners so that the odd time that they do appear, the repo owner can just hit retry (although I'd be a bit scared to do this because I'm well-known to ship broken code...). But failures in the registry would need to be handled by us. Adding one more cron action in the registry to list recent runs and retry failed ones wouldn't be too difficult, but it's another moving part to worry about, no matter how small.

I think maybe a good route forward would be to support both cron and issue comment triggers rather than replacing cron. That way:
- everyone using cron continues to get updates as TagBot remains at v1.x
- if people move to issue comments, they can keep an infrequent cron trigger to handle any potential failures

I'll let this sit for some time before digging too deep as I'm sure there's more discussion to be had.

**Comment by DilumAluthge** [comment]
I think I might have a slightly simpler idea. I’ll write it up in a comment later today.

**Comment by DilumAluthge** [comment]
> Less computers in the world running TagBot.

I think this is the main benefit. By reducing the number of TagBot runs, we can reduce the energy footprint, and therefore reduce our environmental impact.

> The General registry will have a new CI step added on merged PRs.

Unfortunately, I think that this is a non-starter. There is a hard cap on how many simultaneous GH Actions jobs we can have running at the same time. If we have a CI step running every time a PR is merged, then we will hit that cap more frequently, and then automerge will get backed up. I don't want to back up the automerge queue.

---

Here is my idea. It involves no modifications to the TagBot code, a small modification to the `.github/workflows/TagBot.yml` workflow file in everyone's repositories, and the addition of a new GitHub Action to the General registry.

We add a new GitHub Action that runs as a cron job on the General registry. It runs e.g. every 20 minutes. (I don't want to run it too frequently, because we risk hitting our cap on parallel jobs, and thus delaying automerge.) This new cron job will do the following:
1. Compile a list of all new releases made in the last 2 weeks. (This is simple: first, make a list of all versions of all packages based on the latest master. Then, check out a commit from approximately 2 weeks ago, and make a list of all versions of all packages based on that commit. Then take the set difference.)
2. For each package that has at least one new release made in the last 2 weeks, check if it is a GitHub repository. If it is, clone it and get a list of all of the tags. If the list of new releases is a (not necessarily proper) subset of the list of all tags, then do nothing. However, if there is a new release that does not have a tag, then we need to ping the repository. We use the GitHub API to get a list of all issues on the repository. If there is an open issue by the `JuliaTagBot` user, we close it. If there is a closed issue by the `JuliaTagBot` user, we reopen it and then we close it. If there are no open or closed issues by the `JuliaTagBot` user, we create a new issue, and then we close it. This serves as a trigger to run the TagBot job.

The recommended `.github/workflows/TagBot.yml` becomes:
```yaml
name: TagBot
on:
  schedule:
    - cron: 0 0 * * 0 # Notice that I have made the TagBot cron job run once a week. This is a fallback, in case the issue-trigged run fails for any reason.
  issues: # I have added this line
    types: [opened, closed, reopened] # I have added this line

jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
         if: github.actor == 'JuliaTagBot' || github.event_name == 'schedule' # I have added this line
```

---

I intentionally chose issues and not issue comments. The opening, reopening, or closing of an issue is a relatively uncommon event. So GitHub doesn't need to do this logic very frequently. In contrast, issue comments are quite frequent. So GitHub would have to do some work every time an issue comment was created. We don't want that.

**Comment by DilumAluthge** [comment]
I'm almost finished with the code that implements this. I'll share it soon.

**Comment by DilumAluthge** [comment]
Also, this cron job doesn't need to be run on the General registry. It can be run everywhere.

So it probably will make the most sense to run the cron job on this repo (the TagBot repo). Then you can give it a PAT for JuliaTagBot. And you can run it every 5 minutes, which is the fastest that GitHub will allow. So then package authors will see their tags getting created approximately 5 minutes after the PR is merged into General, which is very close to instant.

**Comment by christopher-dG** [comment]
Cool idea. What about using `edited` triggers to avoid user notifications?

**Comment by christopher-dG** [comment]
Also where's the number of allowed parallel jobs? I found [this](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits) but it only lists the non-open-source rates.

**Comment by christopher-dG** [comment]
Oh one more thing I thought of: If this registry-wide polling for new versions happens outside of the registry, support for registries that aren't General breaks somewhat. Or at least, the steps to hosting custom registries start to diverge slightly from General.

Also it seems like there's a lot of work being duplicated, i.e. what was described to look up new versions of packages is already exactly what TagBot does. I think I'm still in the "use PR events" camp; I don't see us hitting our concurrency limit except in exceedingly rare circumstances, the work to be done to support the merged-PR strategy is less complex than polling (in my opinion, at least).

**Comment by SaschaMann** [comment]
> Even at the free rate, I don't really see us hitting that.

I think it's much more likely that we'll run into rate limiting before running into an issue where the automerger is blocked. A workflow that sends a single API request with the `github-script` action takes maybe 2-3 seconds in total.

**Comment by DilumAluthge** [comment]
> I think I'm still in the "use PR events" camp; I don't see us hitting our concurrency limit except in exceedingly rare circumstances, the work to be done to support the merged-PR strategy is less complex than polling (in my opinion, at least).

We are planning on adding more CI as part if AutoMerge. See e.g. https://github.com/JuliaRegistries/RegistryCI.jl/issues/120 and https://github.com/JuliaRegistries/RegistryCI.jl/issues/195. Those additional tests will be run concurrently with the main AutoMerge job.

Given that we currently have a TagBot solution that works, I don't think we can justify adding a merged-PR event to the General registry. We need to reserve those resources for the additional CI that we will be adding.

There are three goals here, and they all compete with each other:
1. Energy footprint/environmental impact
2. Latency: how long do you have to wait before the tag is made
3. Permissions: how much permission do you have to give to a third party app

The old TagBot app did a great job at number 1 and number 2. If we need to prioritize number 1 and number 2, we should go back to the TagBot app.

However, the decision was made to stop using the TagBot app and instead use the TagBot GitHub Action. This is worse for number 1 and number 2, but is better for number 3 because you don't have to trust a third-party app.

I think we need to decide what is most important. If number 1 and number 2 are most important, then we should go back to the TagBot GitHub app. If number 3 is most important, then we stick with the current TagBot GitHub Action with the cron job setup.

**Comment by DilumAluthge** [comment]
> I think it's much more likely that we'll run into rate limiting before running into an issue where the automerger is blocked.

Both are concerning to me. The AutoMerge bot uses the GitHub API extensively.

**Comment by DilumAluthge** [comment]
I think we have two good options:
1. The old TagBot GitHub app
2. The new TagBot GitHub Action, running as a cron job

I don't see how we can justify putting a burden on the General registry (whether it is on concurrent jobs, or the API rate limit, or both) to seek a third solution.

**Comment by christopher-dG** [comment]
Alright, let's scrap this for now. I still think there are improvements to be had but maybe we'll need to wait for better support from GitHub.

**Comment by DilumAluthge** [comment]
GitHub has started disabling scheduled workflows on repos that have had 60 days of inactivity.

Given this, I now agree with @christopher-dG that we will need to implement the issue trigger approach.

**Comment by chriscoey** [comment]
I seem to have hit the rate limit for tagbot:
https://github.com/chriscoey/Hypatia.jl/runs/1208874995?check_suite_focus=true

```Processing version v0.1.0 (3b21dc3695138fdec081657d7b2111fbf698b473)
Generating changelog for version v0.1.0 (3b21dc3695138fdec081657d7b2111fbf698b473)
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 86, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 444, in create_release
    log = self._changelog.get(version, sha)
  File "/root/tagbot/action/changelog.py", line 192, in get
    data = self._collect_data(version, sha)
  File "/root/tagbot/action/changelog.py", line 179, in _collect_data
    "pulls": [self._format_pull(p) for p in pulls],
  File "/root/tagbot/action/changelog.py", line 179, in <listcomp>
    "pulls": [self._format_pull(p) for p in pulls],
  File "/root/tagbot/action/changelog.py", line 149, in _format_pull
    "merger": self._format_user(pull.merged_by),
  File "/root/tagbot/action/changelog.py", line 125, in _format_user
    "name": user.name or user.login,
  File "/usr/local/lib/python3.8/site-packages/github/NamedUser.py", line 270, in name
    self._completeIfNotSet(self._name)
  File "/usr/local/lib/python3.8/site-packages/github/GithubObject.py", line 299, in _completeIfNotSet
    self._completeIfNeeded()
  File "/usr/local/lib/python3.8/site-packages/github/GithubObject.py", line 303, in _completeIfNeeded
    self.__complete()
  File "/usr/local/lib/python3.8/site-packages/github/GithubObject.py", line 310, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for installation ID 6693679.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Response (200): {
  "status": "Submitted error report"
}
```

**Comment by christopher-dG** [comment]
Yeah, that happens sometimes. It can generally be ignored.

**Comment by christopher-dG** [comment]
Okay, so I'm gonna start implementing this:

a) On registry PR merge, we figure out what repo the package belongs to, and if TagBot is enabled on that repo, find an issue created by JuliaTagBot, creating one and instantly closing it if there isn't already one, and comment on the issue. This comment is not used as a source of information, only as a trigger.

b) The TagBot action reacts to the new issue comment by JuliaTagBot, and runs TagBot in exactly the same way it does currently: it looks to the registry to find any new versions that were released in the last few days.

c) Once a day, the registry will look at all the PRs that have been merged in the last day. For each PR, look at the repo to see if the corresponding Git tag has been created (this indicates that TagBot ran successfully in the repo). If there is no  Git tag, send the notification again. This helps us deal with any failures, such as the notification failing to send due to GitHub downtime, or a bad configuration preventing TagBot from running properly (SSH keys, etc.). It gives TagBot N tries instead of just one, where N is the number of lookback days that TagBot uses (3, by default).

TagBot will remain v1, since only the trigger is changing and not the actual functionality.
The new workflow syntax will look like:

```yml
on:
  issue_comment:
    types:
      - created
jobs:
  TagBot:
    if: github.actor == 'JuliaTagBot'
    # ...
```

The `github.actor` value can be changed to work with custom registries and such. 

IMO this setup is quite nice because users will get tags basically instantly, and it's still quite fault tolerant. And it reduces the number of TagBot hugely.
