### ISSUE TITLE
internal error when running your job

### ISSUE THREAD

**Issue by tpapp** [JuliaRegistries/TagBot#134]
I have been getting errors like this for many of my packages in the last few hours:

https://github.com/tpapp/DynamicHMC.jl/actions/runs/75945276

I am not sure what is going on, TagBot worked fine on these packages and I did not change anything recently.

**Comment by christopher-dG** [comment]
GitHub's fault: https://www.githubstatus.com/incidents/2wx06v7dbzhg

Yet another reason I'd like to get off of cron jobs.

**Comment by tpapp** [comment]
Thanks, please close this if you consider it resolved.
