### ISSUE TITLE
Recent failures

### ISSUE THREAD

**Issue by timholy** [JuliaRegistries/TagBot#136]
I've had a lot of spam over the last few days about TagBot failures, but I don't see recent changes to the code. Anything to do about this?

**Comment by christopher-dG** [comment]
Can you link one of the errors? I'm pretty sure it's just GH downtime.
The only thing you can really do is decrease the frequency, or disable the email notifications if you haven't already.
Stuff like that is why I wish we had something other than cron.

**Comment by timholy** [comment]
https://github.com/timholy/CoordinateSplittingPTrees.jl/actions/runs/78958550

**Comment by christopher-dG** [comment]
Yeah that is very much something we don't have control over... 😢
