### ISSUE TITLE
Manually trigger TagBot

### ISSUE THREAD

**Issue by omus** [JuliaRegistries/TagBot#148]
I encountered a situation where actions for [CodecLz4.jl](https://github.com/JuliaIO/CodecLz4.jl) were disabled when the package was registered. I've re-enabled actions for the repo but the latest execution of [TagBot was successful](https://github.com/JuliaIO/CodecLz4.jl/runs/667684721?check_suite_focus=true) but it didn't create the tag. I believe I can extend the [lookback](https://github.com/JuliaRegistries/TagBot#lookback-period) to mitigate the problem but it seems annoying I need to make a new commit to trigger tag bot. Could we introduce a commit trigger similar to how the JuliaRegistrator works to address these kinds of issues?

**Comment by christopher-dG** [comment]
#66 

You can try to follow the logic of `tagbot/action/__main__.py`, filling in the commit SHA and release number manually. But yeah I should really make this nicer.
