### ISSUE TITLE
Missing way to provide URL of self-hosted github and credentials.

### ISSUE THREAD

**Issue by racinmat** [JuliaRegistries/TagBot#152]
So far the `repo.py` has hardcoded
```
self._gh = Github(token, per_page=100)
```
but it would be very useful to provide additional parameters, like
```
self._gh = Github(token, per_page=100, base_url='https://git.our_company.com/api/v3', client_id=client_id, client_secret=client_secret)
```
in case of self-hosted TagBot.
I think there should be something like gh_kwargs parameters in the `__init__` method that be generic and allow passing additional parameters.
Should I make a PR?

**Comment by christopher-dG** [comment]
Thanks for reporting these! TagBot was not made with support for self-hosted GitHub because I didn't know of any orgs using it 🙃. I'll take a bit of time to look into this myself, and probably request your review on any PR I put up if that's ok!

**Comment by racinmat** [comment]
I already made some changes locally to make it working, so I can just put them to PR.
