### ISSUE TITLE
TagBot run failure

### ISSUE THREAD

**Issue by andreasvarga** [JuliaRegistries/TagBot#153]
I hope this is the right place to request help. 

I just successfully registered a new version `v1.0.1` of the package [MatrixPencils.jl](https://github.com/andreasvarga/MatrixPencils.jl) and expected to get the newly generated release number. But, I got the following notification: `Run failed for master (ec10a59)` and a link to [results](https://github.com/andreasvarga/MatrixPencils.jl/actions/runs/110459710). The registration of the previous version 
`v1.0.0`  went without problems.

I would appreciate any hint to recovering from this failure.

**Comment by christopher-dG** [comment]
Looks like GitHub flakiness to me, it's never reaching any TagBot code. It should just fix itself soon.

**Comment by christopher-dG** [comment]
Yeah the same thing is happening here: https://github.com/JuliaRegistries/General/actions/runs/110526336

So nothing on your end, just sit tight and let GitHub fix it 🙂
