### ISSUE TITLE
What's this PR?

### ISSUE THREAD

**Issue by cormullion** [JuliaRegistries/TagBot#172]
This appeared at https://github.com/cormullion/tag-bot/pull/1

<img width="1117" alt="Screenshot 2020-09-02 at 09 59 44" src="https://user-images.githubusercontent.com/52289/91961401-0b63dc00-ed03-11ea-896d-9ba61676ceb2.png">

I've no idea what it is, though.

**Comment by fredrikekre** [comment]
Looking at the account it looks like a spam-bot or something. I would just close the PR and report the user.

**Comment by cormullion** [comment]
OK, thanks. Is it a security risk, or just spam?

**Comment by fredrikekre** [comment]
Just spam it looks like, but IDK.
