### ISSUE TITLE
Support for private registries

### ISSUE THREAD

**Issue by ancapdev** [JuliaRegistries/TagBot#173]
Registry is configurable, but I've not been able to get this to work with a private registry (e.g., through ssh deploy keys), and as far as I can tell from the code only the repo itself makes use of such config.

Would it be much work to enable the necessary configuration for private (github.com hosted) registries, or is there perhaps a way I've missed?

**Comment by christopher-dG** [comment]
The registry is never cloned, it's only accessed via API. So although this is not a great solution, you should be able to get it to work by using a [personal access token](https://github.com/JuliaRegistries/TagBot#personal-access-tokens-pats) with access to both your repo and your registry.

**Comment by ancapdev** [comment]
Thanks, that does seem to work, so I'll use that for now.

Not ideal security wise, since the PAT inherits user permissions for repo access, and locking that down more by having a user per repo isn't scalable. If there's a way to modify TagBot to use separate PATs for the registry (e.g., under a read-only user) and the repo (e.g., the standard GITHUB_TOKEN), it would be a nice improvement.
