### ISSUE TITLE
TagBot experienced an unexpected internal failure - bad object

### ISSUE THREAD

**Issue by captchanjack** [JuliaRegistries/TagBot#174]
Hi I recently registered a new package https://github.com/DeloitteDigitalAPAC/LightOSM.jl

I accidentally squashed the commit v0.1.0 was pointing to, and now TagBot won't auto tag/release this version.

Is there a way around this?

![image](https://user-images.githubusercontent.com/53301102/93672025-f486fd00-faea-11ea-8f04-0032bc8542bd.png)

**Comment by christopher-dG** [comment]
What commit would you like the tag to point at? It should have identical content to what's held in the registry. I can update the merged registry PR so that a different commit gets chosen.

**Comment by captchanjack** [comment]
That's my bad I knew squashing commits was going to lead to something like this, I'll be careful next time!

Could you help tag v0.1.0 with commit 93e61990308cda6be5e74acb0583250176a8db00
and v0.1.1 with commit e039f4a0498be7884361bad0d069135a6d57c644

Thanks Chris!

**Comment by christopher-dG** [comment]
Ok, I've edited the registry PR metadata, so the next time TagBot runs it should create the appropriate tags.

**Comment by captchanjack** [comment]
Hi Chris, sorry to bother again but still seems to be pointing at the wrong commits!

![image](https://user-images.githubusercontent.com/53301102/93693640-e1ede180-fb45-11ea-9d5d-aa4bacfc81be.png)

**Comment by christopher-dG** [comment]
In this case it's because the content at the commits you provided doesn't match what was registered. It's probably best to just manually create those two tags and accept that they're very slightly incorrect.

**Comment by captchanjack** [comment]
Got it, will do, thanks Chris
