### ISSUE TITLE
Duplicated release note in a backport release

### ISSUE THREAD

**Issue by tkf** [JuliaRegistries/TagBot#175]
I released a backport of Aqua [v0.4.11](https://github.com/JuliaTesting/Aqua.jl/releases/tag/v0.4.11) ([TagBot log](https://github.com/JuliaTesting/Aqua.jl/runs/1179954556?check_suite_focus=true#step:3:42)) after releasing Aqua [v0.5.0](https://github.com/JuliaTesting/Aqua.jl/releases/tag/v0.5.0) ([TagBot log](https://github.com/JuliaTesting/Aqua.jl/runs/1179759003?check_suite_focus=true#step:3:41)).  Strangely, it looks like the release note of v0.4.11 and v0.5.0 are the same.  Is this expected? Is there a way to avoid this?

**Comment by christopher-dG** [comment]
The way the issue/PR collection works is basically just time based, ending at the time of the commit being registered, and starting at the time of the last tag. The "last tag" is according to SemVer, not time, so in both of your cases it was 0.4.10 (despite 5.0 being newer when 0.4.11 was being created). So yes, this is expected.

IMO this system works better than the alternative (start at the time of the chronologically previous tag) in a world where version numbers are almost always going up, and backports are much more a special case.

**Comment by tkf** [comment]
Thanks for the explanation. If the last tag is found via SemVer, this could actually be the desired behavior (i.e., 0.4.x users can see what is backported). I'll keep using the vanilla TagBot setting and see what it's like.

**Comment by christopher-dG** [comment]
Worst case, you can just remove the irrelevant entries yourself after the fact :)
