### ISSUE TITLE
Did not find any versions

### ISSUE THREAD

**Issue by fonsp** [JuliaRegistries/TagBot#201]
https://github.com/JuliaPluto/PlutoSliderServer.jl/runs/2414759608?check_suite_focus=true#step:3:38

My TagBot is not creating a release, with output:
```
No new versions to release
```

Even though my package is released:
https://github.com/JuliaRegistries/General/tree/master/P/PlutoSliderServer
and no releases are tagged yet:
https://github.com/JuliaPluto/PlutoSliderServer.jl/tags

**Comment by fonsp** [comment]
(I ran the tagbot with a manual dispatch)

**Comment by christopher-dG** [comment]
Looks like the release is too old. See the `lookback` input, you can also set it as a variable for the manual dispatch instead of hardcoding it.

**Comment by fonsp** [comment]
Thanks!

**Comment by christopher-dG** [comment]
Was just in the middle of adding an example, I'll post it anyways for future readers:

```yml
on:
  workflow_dispatch:
    inputs:
      lookback:
```

When triggering the workflow, you'll have the option of setting a value for `lookback`, which is the max age, in days, of new releases that will be found.

(this can also be done for any other input)

**Comment by fonsp** [comment]
Oh that's neat, thank you!
