### ISSUE TITLE
Tags the wrong commit

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/TagBot#21]
For example, I instructed Registrator to register [this](https://github.com/mimiframework/Mimi.jl/commit/f7ccf6085211e20c65fc732ac20de415add04e57#comments) commit. It did that properly. But then TagBot tagged [this](https://github.com/mimiframework/Mimi.jl/commit/89cd2bc2aa1ba6db05e3f72aa296e3b52ea795b6) commit instead.

I assume that the problem here is that I'm asking Registrator to register a commit that is a) on a branch that is not `master`, and b) not at the tip of that branch. Still, it seems to me it should handle that properly.

I have to fix the tag in that repo now because it is messing up our dev flow, so you won't be able to see the incorrect tag for more than a few seconds, until I fix it.

**Comment by fredrikekre** [comment]
The tag is https://github.com/mimiframework/Mimi.jl/releases/tag/v0.8.7 though?

**Comment by davidanthoff** [comment]
Yeah, as I wrote above, I fixed it manually because this is a production package and I don't want the wrong tag to hang around. But it originally tagged the wrong commit.

**Comment by christopher-dG** [comment]
Sorry, looks like I left out the commit sha from the tag command in #12.

**Comment by davidanthoff** [comment]
@christopher-dG Thanks! I assume that the new version is already deployed?

**Comment by christopher-dG** [comment]
Yep, since yesterday.

**Comment by davidanthoff** [comment]
Great, thanks!
