### ISSUE TITLE
TagBot fails to push tags after adding DOCUMENTER_KEY

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaRegistries/TagBot#220]
Since I added the DOCUMENTER_KEY as ssh key to TagBot it can't push Tags anymore see https://github.com/JuliaPlots/Plots.jl/runs/4480931845?check_suite_focus=true#step:3:44 and https://github.com/JuliaDocs/Documenter.jl/issues/1737

Am I missing something? Or how can I debug this?

**Comment by fredrikekre** [comment]
Just to clarify: the key has permissions for Plots.jl?

**Comment by BeastyBlacksmith** [comment]
Well its added as a deploy key to `PlotDocs.jl` and therefore has write permissions for `PlotDocs.jl` which is needed such that the Documentation can be deployed. I tried to also add it as deploy key to `Plots.jl` but thats not allowed by github.

I'll try to give TagBot its own key. I thought it needs to be the same as the DOCUMENTER_KEY, so it can trigger the action.

**Comment by fredrikekre** [comment]
TagBots push the tag to the repo itself (Plots.jl), so that needs to have write permissions on Plots.jl. You can add another key to push docs from Plots.jl to PlotDocs.jl

**Comment by BeastyBlacksmith** [comment]
With its own key it works.
