### ISSUE TITLE
TagBot fix not working?

### ISSUE THREAD

**Issue by darrencl** [JuliaRegistries/TagBot#224]
Hi,

I have been away from Julia for a while. When I use the registrator to register a new version, seems that my `TagBot.yml` needs to be updated to match the newer version (hence my new version was not tagged). In the issue, there is an instructor to comment `TagBot fix` if I wanted the automatic PR to update `TagBot.yml`. However, as you can see in my issue (https://github.com/darrencl/FeatureSelectors.jl/issues/7), I have commented as per the instruction but there were no action until now (it has been more than a day). 

Could anyone point out which part I did wrong?

Thanks!

**Comment by DilumAluthge** [comment]
@christopher-dG ^
