### ISSUE TITLE
TagBot internal failure 

### ISSUE THREAD

**Issue by jd-lara** [JuliaRegistries/TagBot#226]
The action of TagBot is finishing successfully but not making the release and it provides a cryptic error about internal failure. 

https://github.com/NREL-SIIP/PowerFlows.jl/actions/runs/2030970328

**Comment by SimonDanisch** [comment]
I have the same problem: https://github.com/JuliaGizmos/Observables.jl/runs/6255860921?check_suite_focus=true

**Comment by jd-lara** [comment]
This issue is caused by the fact that the default names of the branch is now `main` and not `master` in the actions.

**Comment by henry2004y** [comment]
> This issue is caused by the fact that the default names of the branch is now `main` and not `master` in the actions.

How did you fix this? Changing the default branch name from `master` to `main`? I tried the other way by adding `branch: master` in the TagBot.yml, but somehow it didn't work...
