### ISSUE TITLE
Custom release notes in addition to autogenerated ones

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/TagBot#24]
Would be nice to be able to combine both custom release notes and the generated ones to include a sort of summary:

```
Registrator register()

Release notes:

This release has 9999 bug fixes.

{{changelog}}

This comes at the end. Thanks for reading?
```

Might be nice to insert anything above `{{changelog}}` after the generated header, i.e.:

---

## [v0.1.1](url) (2019-01-01)

[Diff since v0.1.0](url)

### Summary

This release has 9999 bug fixes.

**Closed issues:**

- a (#100)
- b (#200)

**Merged pull requests:**

- c (#300) (author)

This comes at the end. Thanks for reading?

**Comment by JeffreySarnoff** [comment]
all for it

**Comment by aminya** [comment]
Is this implemented? I prefer to write my own summary instead of issues and pull requests.
I use Project section of Github for scheduling and tracking, and a lot those are not issues

**Comment by christopher-dG** [comment]
You can write custom release notes but the `{{changelog}}` bit isn't implemented (see the registrator docs).

**Comment by christopher-dG** [comment]
The new plan for this is an option for a fully custom changelog template using [Jinja](https://jinja.palletsprojects.com). I'm gonna experiment with forking the changelog generator to emit more detailed JSON instead of the rendered Markdown. If that fails I'll fall back to just parsing the output.
