### ISSUE TITLE
Don't compare with future releases

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/TagBot#26]
E.g. here, we should compare with v0.18.6, not v0.19.1: https://github.com/JuliaOpt/JuMP.jl/releases/tag/v0.18.6

**Comment by christopher-dG** [comment]
The bug is not ours unfortunately. There are a few things I'd like to fix in the generator, I might spend some time with it eventually.

**Comment by christopher-dG** [comment]
https://github.com/github-changelog-generator/github-changelog-generator/issues/497

**Comment by christopher-dG** [comment]
Fixing the link manually would be pretty easy but I don't think we actually want to do that, because then the list of issues/PRs is no longer accurate.
