### ISSUE TITLE
Could not find registry PR

### ISSUE THREAD

**Issue by cadojo** [JuliaRegistries/TagBot#262]
I'm seeing warnings in my TagBot CI job logs. A release and tag are created successfully, but no documentation build is triggered. Are these two issues potentially related?

https://github.com/cadojo/HorizonsAPI.jl/actions/runs/4848205877/jobs/8639117151#step:3:40

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLSensitivity.jl/actions/runs/4870575841/jobs/8686495391#step:3:44 same here.

**Comment by ChrisRackauckas** [comment]
Looks like a duplicate of https://github.com/JuliaRegistries/TagBot/issues/258
