### ISSUE TITLE
Release notes are ignored

### ISSUE THREAD

**Issue by maleadt** [JuliaRegistries/TagBot#263]
I made a release with manual release notes:
- https://github.com/JuliaGPU/Metal.jl/commit/9a72b9c68a5d4fb81e517a457d5cfbc16f44e08a#commitcomment-120342604
- release-notes got picked up by Registrator: https://github.com/JuliaRegistries/General/pull/86662

However, the TagBot-created release still only has the autogenerated release notes: 
<img width="850" alt="image" src="https://github.com/JuliaRegistries/TagBot/assets/383068/ddb7a4a9-e621-4c14-aa4f-85766543355c">

Screenshot because I'll be manually editing the release notes.

**Comment by IanButterworth** [comment]
It would be great to have this. 

It seems like the `custom` field is where it should be, and the default template does appear to show if nonempty
https://github.com/JuliaRegistries/TagBot/blob/214862eefbed0334bbbdc061c1f9671ce041ca21/action.yml#L76-L78

So somehow the data structure field `custom` isn't populated
