### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/TagBot#30]
I've just spent the evening playing around with GitHub Actions and I think it could make things a lot nicer. It's been discussed a bit on Slack too. 

Early idea stage, this is an ugly wall of text.

~~### Step 1 (Registrator)
Registrator comments on a commit in the package repo when it merges a PR into General. This means no more awkward listening for events in a separate repo.
The comment contains at least the version and commit sha to be tagged.
The commit that gets the comment doesn't really matter as long as the comment itself contains enough information.
I guess it can decide whether or not to do this by looking for a GitHub workflow file in the target repo.
Even just this step would make TagBot a lot less janky.~~

~~### Step 2 (parse + validate)
At this point we're in a workflow in the package repo that responds to commit comments.
Parse and validate the comment etc., then pass along the commit sha + tag name to be created.
This is code that would belong in this repo, since it's Julia-specific.~~

### Step 1 (Registrator)

Registrator sends a [repo dispatch event](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) to the repository whose package was just merged.
The payload is JSON, and the event name identifies it as a registration event, so no validation or special parsing is required.

Grrrrrr, this strategy requires the sender of that dispatch event (aka Registrator or something associated with General) to have repo write permissions, so we're not doing that. Back to the old plan.
I also don't think GitHub Actions has a trigger for commit comments, so a workaround would be to create and immediately close an issue, and always comment on that issue. Feature request for `on: commit_comment` [here](https://github.community/t5/GitHub-Actions/Can-we-have-on-commit-comment-as-a-trigger/m-p/36667#M2647).

### Step 2 (make tag)
 Super easy if you disregard GPG signing, I'm not quite sure how that would work now, but I'm sure it's doable. This can be something generic, nothing is Julia-specific. It just needs options to set the tag name and commit to be tagged (since the commit that was commented on is not necessarily the one that we should tag).

### Step 3 (create changelog)
Run the changelog generator, and extract out the section for the newly created tag. I've started looking into this [here](https://github.com/christopher-dG/changelog), since it's also not Julia-specific at all.
This job could just dump the results to a file rather than creating the release, and pass along the filename.

### Step 4 (create release)
Easy, and not specific to Julia at all. Just need to be able to configure the release body, name, and sha.

---

While most of the pieces can be useful to anyone, I'm not sure if we'll find pre-made stuff that fits perfectly since it needs to be configurable in just the right ways.

It would kind of be a shame if #29 went to waste, because I'm quite proud of that code tbh. At least some of it can be reused, even if it's in other repos. But if it amounts to a nicer system for the community, it's worth it.

Oh and... we could write this code in Julia :upside_down_face: 

---

The above sketch outlines a modular system, but as an initial draft I think I'm just going to combine everything into the same action.

**Comment by SaschaMann** [comment]
**Re. Step 3:**
> Super easy if you disregard GPG signing, I'm not quite sure how that would work now, but I'm sure it's doable. 

The action docs contain a [workaround](https://help.github.com/en/articles/virtual-environments-for-github-actions#limits-for-secrets) on how to save large secrets like GPG keys to be used in actions. One could store a package-specific release signing key in the repo itself using the method above and use that for signing the tags. The public key would be signed by the authors/maintainers.

There are probably better ways, though...

**Re. Step 4:**
I don't know what you currently use to generate changelogs and how much effort it would take to port it to an action but it might be worth taking a look at actions on the marketplace that can generate changelogs, e.g. [Release Drafter](https://github.com/marketplace/actions/release-drafter).

---

Automatic tagging without relying on an external app that requires write access would be really useful; I'm looking forward to where this is going :)

**Comment by christopher-dG** [comment]
Yeah, the big secrets thing is what I was looking at too, I didn't dig too deep.

Changelogs are generated by [this](https://github.com/github-changelog-generator/github-changelog/generator), which is quite non-trivial and does a lot of work for us. Wrapping it in an action is pretty simple, thankfully. 

Also to note is that unfortunately,.this isn't any more constrained than a GitHub App... You have to provide a token and by default it can do basically anything to your repo (see [here](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret)).

**Comment by SaschaMann** [comment]
> Also to note is that unfortunately,.this isn't any more constrained than a GitHub App... You have to provide a token and by default it can do basically anything to your repo (see here).

Yes but unlike apps I don't have to trust someone else with it or deal with hosting it myself on non-GitHub infrastructure, so it's definitely an improvement.
