### ISSUE TITLE
Provide optional release branch merging option

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/TagBot#34]
Would you be open to add another optional feature that does the following: whenever it finds a new release and tags it, it also looks for a branch with the name `release-1.2.3`, and if that exists try to merges that into `master`, but only if it can be done with a fast-forward merge. If that succeeded, it also deletes the branch. If the ff merge didn't work, it opens a PR to merge that branch into `master`. The whole thing could be opt-in via a config option for the action.

This is the backstory for this feature: I have a rewrite of PkgDev.jl that provides a `tag` function. When you call `PkgDev.tag("MyPkg")`, the following things happen:
1. it figures out what the next release version shall be (you can also specify that in the call to `tag`)
2. it will create a new branch `release-1.2.3` for that version
3. it sets the version field in `Project.toml` to that version and commits
4. it modifieds the version field in Project.toml` to `1.2.4-DEV` and commits
5. it pushes that branch to `origin`
6. it then uses `Registrator.jl` to open a PR against the registry where this package is registered (with support for public and private registries) that registers the new version

At that point it stops.

If TagBot would do the additional things that I mentioned above, then we would have a complete, super easy package tagging story, IMO. Essentially as a pkg dev I would call `Pkg.tag("MyPackage")`, tne then the bots would do everything else, from modifying the `Project.toml`, to opening PRs that trigger various checks.

I'd be happy to help write the code, just wanted to check whether this might be acceptable in this repo first :)

**Comment by davidanthoff** [comment]
Bump, any progress on this? Now that package butler enables tagbot, this would be awesome to have :)

**Comment by christopher-dG** [comment]
Sorry, I'm swamped for time lately. It'll happen in a couple weeks I'd wager.

**Comment by christopher-dG** [comment]
Okay, I'm looking into this now. One question comes to mind:

Does it matter if this merge process happens before or after the release is created? One difference that I can think of is if we merge before we tag, we can use `master` as the release target and avoid the problem outlined in #10.

The more I think about this, I don't think the order matters at all, since the release is not attached to a Git branch but rather a Git commit. So if the merge is fast-forward as it should be, nothing actually changes. But I just want to make sure that this sounds sane.

**Comment by davidanthoff** [comment]
Yes, I think that is right, the order doesn't really matter at all, so perfectly fine to first merge and then tag.

I guess the other case is that we can't fast-forward merge, because someone has pushed something to `master` in the meantime. I suggested above that in that case a PR could be opened to merge the `release-1.2.3` branch into `master`, but I think the tagging should still just happen, right?

**Comment by christopher-dG** [comment]
Yep, if we can't FF then a PR will be made, and the release will still be made but with the target being the commit SHA instead of `master`. I don't think we should use the `release-x.y.z` branch name as the target because then the "n commits to BRANCH since this release" will not be useful.
