### ISSUE TITLE
SSH/GPG keys with passwords

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/TagBot#37]
Currently there's nothing to input a password to GPG, and this is blocking me from using my own GPG key. I've tried a few things but I need to do more digging.

**Comment by DilumAluthge** [comment]
For what it’s worth, I don’t think you should upload your own personal GPG key anywhere.

I think the best practice here will be:
1. Create a GitHub bot user `MyBot`
2. Create a new GPG key, and upload the public key to the GitHub profile of `MyBot`
3. Upload the private key to TagBot

So your tags will be signed by `MyBot`.

**Comment by christopher-dG** [comment]
If I used GPG for anything but Git, then I'd probably agree, but as it stands the consequence of losing my GPG key is basically the same as losing another one made for a bot

**Comment by christopher-dG** [comment]
Low priority, but this could be a thing again, SSH keys too.
