### ISSUE TITLE
Don't create annotated tags

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/TagBot#40]
I've kind of wanted to get rid of annotated tags for a while because it makes things a lot simpler (we get to skip the entire tag creation step), but I think this is an actual good reason:

https://github.com/JuliaRegistries/General/pull/5999#issuecomment-559625219

Any time that a release contains modified GitHub Actions files, I'm pretty sure that the tag will fail. Of course, we could just ignore the failure if we wanted.

The only benefit of annotated tags is the option to supply a GPG key, but I anticipate that to be a seldom used feature. It was nice to have when it was easy to centrally set up, but I don't think we really get much out of it seeing as the tags aren't actually used for anything important and exist only as a convenience now.

**Comment by DilumAluthge** [comment]
> The only benefit of annotated tags is the option to supply a GPG key, but I anticipate that to be a seldom used feature.

It is very important to us that we are able to GPG-sign our tags.

What if you allow us to pass in our own personal access token, and then TagBot uses our PAT? That would solve the problem in https://github.com/JuliaRegistries/General/pull/5999#issuecomment-559625219

You could make it an opt-in feature. If a user does not provide a PAT, then you make a lightweight tag. But if the user provides both a PAT and a GPG key, you make an annotated tag, you GPG-sign the tag with the user’s GPG key, and you push the tag by authenticating with the user’s PAT.

**Comment by christopher-dG** [comment]
Yikes, even more complex... What about a hook system that let TagBot broadcast "hi, i'm about to create these releases at these commit. do you want to do anything before that happens like creating matching tags? if so, you have 3 minutes." I think we could do that by sending a repository dispatch event.

Can I get some context on the importance of signed tags for you (or your lab, presumably)? I can't tell any big benefits when the lightweight tag points at a signed commit, but I might not see the whole picture here.

**Comment by DilumAluthge** [comment]
> Can I get some context on the importance of signed tags for you (or your lab, presumably)? I can't tell any big benefits when the lightweight tag points at a signed commit, but I might not see the whole picture here.

There’s the catch :( the merge bot we use doesn’t currently sign our commits. But I guess the solution is probably to fix the merge bot to sign its commits.
