### ISSUE TITLE
Find commits on non master branches

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/TagBot#41]
When I tag a new release, I typically create a branch called `release-1.2.3`, then update the `version` field in Project.toml. with a commit on that branch, push that branch, trigger registrator on that commit on that branch.

So when things are merged in the registry, the commit that corresponds to the tag will _not_ be on `master` yet. It seems that tagbot then doesn't find the commit? Is it only looking in the history of `master` for commits that might correspond to a new tag?

The process I described above is also what `PkgDev.tag` does.

I could see two solutions: 1) just check commits in all branches, or 2) also look for commits in branches that are named `release-1.2.3` specifically.

**Comment by christopher-dG** [comment]
This should be fixed now, let me know if it works or not for you please!

**Comment by davidanthoff** [comment]
Yep, works, thanks for the quick turnaround!
