### ISSUE TITLE
Seems to not find commits

### ISSUE THREAD

**Issue by davidanthoff** [JuliaRegistries/TagBot#42]
See for example [here](https://github.com/queryverse/VegaDatasets.jl/commit/7c161cb1b51272bc786a409948ce5bb967ad82b9/checks?check_suite_id=358861202). The commit exists, but it doesn't seem to find it?

**Comment by christopher-dG** [comment]
I think I've identified the issue, and you should see the next run (conveniently in just a few minutes) work fine. Turns out the fix to #41 was not quite right.

**Comment by davidanthoff** [comment]
Yep, just created the release, thanks for the quick turnaround :)
