### ISSUE TITLE
Not creating release before creating the changelog

### ISSUE THREAD

**Issue by aminya** [JuliaRegistries/TagBot#46]
Tagbot sends emails that a changelog is being generated, please check back in a few minutes.

It should first generate the changelog and then make a release.

![image](https://user-images.githubusercontent.com/16418197/72073261-d256a180-3304-11ea-92a0-a196adb871e6.png)

**Comment by christopher-dG** [comment]
Fixed in the new GitHub Actions setup, please use that :slightly_smiling_face:. Soon enough there will be a real deprecation of the GitHub App, I just need to find some time for it.
