### ISSUE TITLE
TagBot workflow does not trigger CI, preventing docs for tags

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/TagBot#47]
This is probably known, but I didn't see an issue. The problem, as @SaschaMann pointed me to, is that it's hard to get workflows to trigger other workflows. So when using Github Actions for CI and for tagbot, even adding an `on: release` trigger to the CI workflow does not cause the tagbot workflow's tag to cause CI to run (I know this because I tried just now with the repo https://github.com/ericphanson/UnbalancedOptimalTransport.jl). Hence, the docs don't get built for the tag, and one doesn't get release docs (only dev docs).

I'll switch back to the bot version of tagbot instead of the workflow (which also has the advantage of being instant instead of waiting for a tag). But maybe this issue is something to consider re #39.

**Comment by christopher-dG** [comment]
You should be able to fix this by overriding the `GITHUB_TOKEN` repo secret with your own token, but this unfortunately is a GitHub issue.

Relevant info: https://github.com/JuliaDocs/Documenter.jl/issues/1177 and [this GitHub Discourse post](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/27454/highlight/true#M302).

**Comment by DilumAluthge** [comment]
@christopher-dG Does TagBot allow you to provide your own personal access token for use by TagBot?

**Comment by DilumAluthge** [comment]
Whoops I see how easy it is. Just specify `token:`.

I’ll make a PR to add this to the TagBot documentation.

**Comment by christopher-dG** [comment]
Really you don't need to change the workflow at all, you just need to set the repo secret in the settings.

**Comment by DilumAluthge** [comment]
If you try to add a repo secret named `GITHUB_TOKEN`, you get the following error:
> Failed to add secret. Name is invalid. 

If I understand correctly, GitHub does not allow you to create a repo secret with a name that begins with `GITHUB_`. Those names are reserved for GitHub.

**Comment by christopher-dG** [comment]
Oh, weird. I thought I read that you could "override" the default one by doing that, but I guess not.

**Comment by DilumAluthge** [comment]
> Note: GitHub reserves the GITHUB_ environment variable prefix for internal use by GitHub. Setting an environment variable or secret with the GITHUB_ prefix will result in an error.

From: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables

**Comment by christopher-dG** [comment]
Lame. I guess we can recommend setting a `PERSONAL_ACCESS_TOKEN` secret then and updating the config appropriately then.

**Comment by DilumAluthge** [comment]
#48
