### ISSUE TITLE
App is installed for user but the repository is not enabled

### ISSUE THREAD

**Issue by tlienart** [JuliaRegistries/TagBot#53]
Hello!

I  tried to move some of the repos I work on to  use the Github workflows which I think is the recommended way now but I keep getting errors like: https://github.com/JuliaRegistries/General/pull/9002#issuecomment-583295039 

However on the README  it says specifically that  the only thing to do  is to add the `TagBot.yml` file which I have done: https://github.com/alan-turing-institute/MLJModelInterface.jl/blob/master/.github/workflows/TagBot.yml 

Is  there an additional step that must be done that would not be documented?

Thanks!

**Comment by tlienart** [comment]
Uh looks like I spoke too soon... https://github.com/alan-turing-institute/MLJModelInterface.jl/releases sorry

**Comment by christopher-dG** [comment]
Yeah, it's a bit out of sync right now - the documentation here refers to the GitHub Action. If you have enabled the GitHub Action (via the `.yml` file), you should uninstall the GitHub App (htttps://github.com/apps/julia-tagbot). The App will be officially deprecated soon.
