### ISSUE TITLE
Are labels like `no changelog` supported in GitHub Action?

### ISSUE THREAD

**Issue by tkf** [JuliaRegistries/TagBot#57]
Old TagBot had [this list of issue/PR labels for excluding items from the changelog](https://github.com/JuliaRegistries/TagBot/blob/45c63403cbb72aaf23958b18c0ca439c25e8658a/README.md#release-notes):

> When using the automatic changelog, you can ensure that certain issues or pull requests are not included.
> These might include usage questions or typo fixes that aren't worth mentioning.
> To exclude an issue or PR, add a label to it with one of the following values:
> 
> - `changelog skip`
> - `duplicate`
> - `exclude from changelog`
> - `invalid`
> - `no changelog`
> - `question`
> - `wont fix`
> 
> You can spell these in a few different ways.
> For example, `no changelog` could be `nochangelog`, `no-changelog`, `no_changelog`, `No Changelog`, `NoChangelog`, `No-Changelog`, or `No_Changelog`.

However, IIUC, it looks like the latest TagBot supports only `changelog-skip`:

https://github.com/JuliaRegistries/TagBot/blob/43c9bdb7c275f6de38e269b2d327d5a40b82bb75/action.yml#L49

Can you add back all the previously supported labels?

**Comment by christopher-dG** [comment]
> However, IIUC, it looks like the latest TagBot supports only changelog-skip:

Yep, correct.

I can definitely add the old behaviour, I think I'll add it as a configuration option too.

**Comment by tkf** [comment]
Thanks a lot! That would be great.
