### ISSUE TITLE
How do I use TagBot?

### ISSUE THREAD

**Issue by eschnett** [JuliaRegistries/TagBot#58]
I see that TagBot "Creates tags, releases, and changelogs for your Julia packages". I also see the detailed instructions for setting up TagBot. But how do I use it – how do I actually create a release? That information seems to be missing from the readme.

Does it depend on tags (Github "releases") I put into the repo (probably not)? Or does it look at the version number I set via `Pkg` (probably)? Does it wait for all tests to pass before it creates a release? What if I tag or increase the version number on a branch – will it wait until the branch has been merged into master? What events should I expect to happen, with what kind of typical delay? What do I do if things don't work, how do I trigger TagBot to have another look? Can TagBot also archive the repo somewhere, e.g. on Zenodo?

**Comment by christopher-dG** [comment]
I guess I kind of forgot to re-add the high-level summary when I rewrote the readme... Probably the most important thing to know is that TagBot only create **Git** tags and **GitHub** releases. To the Julia package manager, these are both not important.

It reacts to your package being registered in a Julia registry like [General](https://github.com/JuliaRegistries/General). The registration process depends on the registry, but for General (the one most packages are registered in), you can use [Registrator](https://github.com/JuliaRegistries/Registrator.jl). 

In the default configuration, TagBot runs on a schedule (every hour). If it didn't work, it'll just try again later. Right now I don't have a good solution for "I just want to tag this version I registered two weeks ago" but I'll do that eventually.
