### ISSUE TITLE
Run cancelled for master

### ISSUE THREAD

**Issue by bjarthur** [JuliaRegistries/TagBot#63]
TagBot is emitting `Run cancelled for master` for NIDAQ.jl, VennEuler.jl, and Morton,jl, but not, for example, for Gadfly.jl and Compose.jl.  The only difference between the broken and working TagBot installations that i can see is the inclusion of `- uses: actions/checkout@v1` in TagBot.yml in those that work.  Don't know where that line came from, but it's not in the TagBot installation instructions in the README.  should it be?  or is something else wrong??  thanks.

**Comment by christopher-dG** [comment]
Hi, thanks for the report. Could you link me one of these broken runs?
The `actions/checkout` step used to be required but it is no longer so. Nowadays the clone isn't used, but it shouldn't cause any problems either.

**Comment by bjarthur** [comment]
you mean this?  https://github.com/JuliaTagBot/Morton.jl/runs/449508393

**Comment by christopher-dG** [comment]
> The following team project collection is stopped: S67vQLYOWNkOyWbJxqTNKAxwigH4rnXS2fDNom0KEAqCA3C2Qn. Start the collection and then try again. Administrator Reason: Actions jobs for this repository have been disabled by GitHub staff. If you are the repository owner, you can contact support via https://github.com/contact for more information

It would appear that GitHub doesn't like when you run an hourly Action on 3700 repositories. But this is in the fork repo, not the parent one. [It seems to be working fine in the parent repo, no?](https://github.com/JaneliaSciComp/Morton.jl/actions/runs/40012483)

**Comment by christopher-dG** [comment]
Closing because as I understand it, this is not an issue in your repos. If I'm wrong please let me know!

**Comment by bjarthur** [comment]
thanks for you help here.  given the problem with hourly actions, perhaps the suggested tagbot install should run daily instead?

**Comment by christopher-dG** [comment]
Hourly actions aren't a problem, but it's definitely exceptional to have thousands of them. I don't foresee any human users running into that. Running it daily is also totally fine!
