### ISSUE TITLE
Easier manual usage

### ISSUE THREAD

**Issue by christopher-dG** [JuliaRegistries/TagBot#66]
If I break something and TagBot goes stops working for a day or whatever, people might miss releases and want to trigger them manually but still get the changelog, ensure that the tag is on the right commit, etc. 
It would be cool to be able to easily run TagBot locally without having to clone the TagBot repo or know an arcane `docker run -e ...` incantation. It might be fun to spin up a web service where you can authenticate with GitHub and run TagBot on a repo of your choosing. :upside_down_face:.

**Comment by tkf** [comment]
A stupid-simple trick might be to create a _PR_ with a patch like this

```diff
diff --git a/.github/workflows/TagBot.yml b/.github/workflows/TagBot.yml
index ade00bef..4581951b 100644
--- a/.github/workflows/TagBot.yml
+++ b/.github/workflows/TagBot.yml
@@ -1,5 +1,6 @@
 name: TagBot
 on:
+  pull_request:
   schedule:
     - cron: 0 * * * *
   push:
@@ -9,7 +10,7 @@ jobs:
   TagBot:
     runs-on: ubuntu-latest
     steps:
-      - uses: JuliaRegistries/TagBot@v1
+      - uses: JuliaRegistries/TagBot@v1.23.45
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           ssh: ${{ secrets.SSH_KEY }}
```

where `v1.23.45` should be replaced with the last working version.
