### ISSUE TITLE
Bunch of failed runs

### ISSUE THREAD

**Issue by vchuravy** [JuliaRegistries/TagBot#67]
I woke up today to a bunch of failed pipelines from TagBot.

- https://github.com/JuliaParallel/ClusterManagers.jl/runs/459790357

- https://github.com/JuliaParallel/MPI.jl/runs/460001965

**Comment by christopher-dG** [comment]
Yeah i made a mistake in the second-last release, it's been fixed. I have a plan to avoid similar errors in the future. Sorry for the noise!

**Comment by vchuravy** [comment]
Thank you for all the work you do

**Comment by tpapp** [comment]
I still get failures, is it the same issue or should I open a new one?

https://github.com/KristofferC/PGFPlotsX.jl/commit/10e19a3f206179242a59de844c14fcb732d2df0c/checks?check_suite_id=473293807

**Comment by christopher-dG** [comment]
That's different. I'll look into it shortly!

**Comment by christopher-dG** [comment]
Ok, that one should be fixed now too.
