### ISSUE TITLE
tagbot creates tags on forks when upstream made a release

### ISSUE THREAD

**Issue by johnnychen94** [JuliaRegistries/TagBot#79]
Just got a notification on my Flux fork https://github.com/johnnychen94/Flux.jl/releases I guess this is unexpected?

![image](https://user-images.githubusercontent.com/8684355/75777884-c41b8380-5d91-11ea-952b-94e4047e729c.png)

**Comment by christopher-dG** [comment]
Oops, yeah that really should not be happening.
I think the best thing to do is to check that the URL in the registry matches the repo where TagBot is running.
