### ISSUE TITLE
TagBot failed with github.GithubException.UnknownObjectException

### ISSUE THREAD

**Issue by tkf** [JuliaRegistries/TagBot#81]
I found this in the error log:

```
##[error]TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 52, in <module>
    versions = repo.new_versions()
  File "/root/tagbot/action/repo.py", line 221, in new_versions
    old = self._versions(min_age=self._lookback)
  File "/root/tagbot/action/repo.py", line 182, in _versions
    contents = self._registry.get_contents(f"{root}/Versions.toml", **kwargs)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 1685, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/v3/repos/contents/#get-contents"}

Response (403): {
  "message": "Forbidden"
}
```

https://github.com/tkf/SplittablesBase.jl/runs/484158558?check_suite_focus=true#step:3:35

**Comment by christopher-dG** [comment]
Two bugs in one!

I thought that [a previous check](https://github.com/JuliaRegistries/TagBot/blob/8115dfc911c9b2872488515be6b4343f5dc820b2/tagbot/action/repo.py#L167-L169) would have guaranteed that the file we're looking for would exist... but apparently something is gone wrong.

And the automatic error reporting is somehow misconfigured and all requests return 403. without ever reaching my code :upside_down_face: 

I'll get right on both of them.

**Comment by christopher-dG** [comment]
Your issue should be fixed by 189876a8105004a7c63dc3cde5c9230ec7f19800, I'll leave this open until I see it work and I fix the second bit.

**Comment by tkf** [comment]
Thanks a lot for super quick fix!

> And the automatic error reporting is somehow misconfigured and all requests return 403.

Yeah, I wasn't sure if I should open an issue as I thought it would be opened automatically.

**Comment by christopher-dG** [comment]
It kind of started working... See the 20 new issues lol. But the particular error being reported is supposed to be ignored... Lots of work to do.

**Comment by tkf** [comment]
Not sure if it is related to the original issue, but here is another strange thing.

TagBot says `No new versions to release`:
https://github.com/tkf/SplittablesBase.jl/runs/484324695?check_suite_focus=true#step:3:35

...while this package is already registered https://github.com/JuliaRegistries/General/pull/10344 and no related release exist yet https://github.com/tkf/SplittablesBase.jl/releases

**Comment by christopher-dG** [comment]
Hm, yeah that really shouldn't be happening either. It's picking up the new version when I run it locally, so I'll check what happens when it runs next. Could you set the repo secret `ACTIONS_STEP_DEBUG` to `true` for me?

**Comment by tkf** [comment]
Here is the log: https://github.com/tkf/SplittablesBase.jl/runs/484463941?check_suite_focus=true#step:3:1

Unfortunately(?), it created the new release, though https://github.com/tkf/SplittablesBase.jl/releases/tag/v0.1.0

**Comment by christopher-dG** [comment]
Well then... My guess is that it was related to #80 but I'm not really sure. Let's just assume it'll keep working...

**Comment by christopher-dG** [comment]
Alright 18835738127124da21fd759a72bf8478c491ccd5 should take care of the error reporting problems. The initial problem of "no requests are going through" was solved by just redeploying... I guess it's flaky.
